[tool.poetry]
name = "sqlmin"
version = "1.1.0"
description = ""
authors = ["Anton Medvedev <anton@medv.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
